### ISSUE TITLE
Still unable to run the project.

### ISSUE THREAD

**Issue by acche** [JeffBNimble/LoLBookOfChampions-swift2-sqlite#3]
Follow the instructions to run both Carthage And Cocoapods to pre-setup the project. But it is still some error occurred while build the project.
## ( Try it on Xcode 7.1 AND Xcode 7.2 Beta 4 )

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:15:64: 'Sink' is not a member type of 'Event<(Uri, ContentOperation), NoError>' (aka 'Event<(NSURL, ContentOperation), NoError>')

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:16:56: 'Sink' is not a member type of 'Event<(Uri, ContentOperation), NoError>' (aka 'Event<(NSURL, ContentOperation), NoError>')

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:21:9: Use of unresolved identifier 'sendNext'

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:31:35: Cannot invoke initializer for type 'AppContentObserver' with an argument list of type '(sink: Observer<(Uri, ContentOperation), NoError>)'

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Actions.swift:72:21: Use of unresolved identifier 'sendCompleted'

---

How can I resolved those error?

**Comment by JeffBNimble** [comment]
The problem is that the Cartfile references the swift2 branch of the ReactiveCocoa framework.

See here: https://github.com/JeffBNimble/LoLBookOfChampions-swift2-sqlite/blob/master/Cartfile

This is generally not good practice since a branch continually changes and can even be deleted. However, I did this because I wanted to use the code that would eventually become the new Swift 2 way of using ReactiveCocoa.

The problem is that they have changed their API and the code I was using no longer works when you pull the latest code from that branch.

I will fix it later today/tonight if I can get to it and will update this thread when it's fixed.

Thank you for bringing this to my attention.

**Comment by JeffBNimble** [comment]
Apologies that it took me so long to address this. I have finally fixed the app. The Cartfile has been updated to reference the correct version of the ReactiveCocoa framework. Please make sure you've updated to Carthage v 0.11.0 and then follow the install instructions in the README. The app will not build and run correctly.
